### ISSUE TITLE
the extension visual studio emmet 2013 requires a version of .net framework which is not installed

### ISSUE THREAD

**Issue by myounus96** [JackyDing/Jacky.Emmet#5]
the extension visual studio emmet 2013 requires a version of .net framework which is not installed
attached log file
[VSIXInstaller_fc22b248-6ae7-493a-9fde-e151554d3c65.txt](https://github.com/JackyDing/Jacky.Emmet/files/681751/VSIXInstaller_fc22b248-6ae7-493a-9fde-e151554d3c65.txt)

**Comment by glazrtom** [comment]
I had this problem too... I edit the extension (I delete verification of .NET framework in file "extension.vsixmanifest" the file you can open in for example in 7-zip...) then it works... You should have instaled .net framework v 4.5 and then install this extension)
by me edited extension download: https://1drv.ms/u/s!Ate252B8I_QLnhZmKA9B8sZuqcZq

**Comment by suyanhanx** [comment]
Hello,tomato4.I had this problem too..But I don't know how to edit the file.The link you post can't use now.Can you post a new link? Thank you very much.

**Comment by suyanhanx** [comment]
Hello,MYounas.Have you solved this problem?I can't find the way to solve this.Please teach me.Thank you very much.

**Comment by suyanhanx** [comment]
My system is windows 10.So it has had the .Net Framework 4.5.

**Comment by glazrtom** [comment]
I don't remember how to do it, but maybe I will remember... Give me a while...

**Comment by glazrtom** [comment]
So
1. download the extension: [https://goo.gl/QZmCiX](url)
2. open it with for example 7zip.
3. open extension.vsixmanifest in text editor
4. delete this line `<Dependency Id="Microsoft.Framework.NDP" DisplayName="Microsoft .NET Framework" Version="4.5" />`
5. now save - 7zip automatically ask you if you want update the file - so yes
Now you have extension without NetF. control. I recommend you to do this only if you know, that you have .Net Framework (and extension don't see him)

**Comment by suyanhanx** [comment]
It takes effect！Thank you very much!
